define("bd/id", [
  "bd"
], function(bd) {
///
// Defines the bd.id class.

bd.id= bd.declare(
  ///
  // Mixin class that provides a read-only id attribute that holds an page-wide unique identifier and registers new
  // instances with the bd.object registry.

  //superclasses
  [],

  //members
  bd.constAttr(
    ///
    //(string) The id attribute value
    ///
    // A document-wide unique identifier. // If an identifier is not provided at construction (the usual case), then
    // an identifier is generated by bd.uid. Recall that bd.uid generates identifiers that are legal JavaScript identifiers.
    "id",

    undefined //default value 
  ),
 
  {
  precreateDom: function() {
    ///
    // Initializes the id attribute and registers this object with the bd.object registry.
    this.inherited(arguments);
    this.id= this.id || bd.uid();
    bd.object.set(this);
  }
});

});
// Copyright (c) 2000-2009, Altoviso, Inc. (www.altoviso.com). Use, modification, and distribution subject to terms of license.
